links:
    - label: interop-2023-offscreencanvas
      results:
        - test: 2d.composite.canvas.copy.html
        - test: 2d.composite.canvas.copy.worker.html
        - test: 2d.composite.canvas.destination-atop.html
        - test: 2d.composite.canvas.destination-atop.worker.html
        - test: 2d.composite.canvas.destination-in.html
        - test: 2d.composite.canvas.destination-in.worker.html
        - test: 2d.composite.canvas.destination-out.html
        - test: 2d.composite.canvas.destination-out.worker.html
        - test: 2d.composite.canvas.destination-over.html
        - test: 2d.composite.canvas.destination-over.worker.html
        - test: 2d.composite.canvas.lighter.html
        - test: 2d.composite.canvas.lighter.worker.html
        - test: 2d.composite.canvas.source-atop.html
        - test: 2d.composite.canvas.source-atop.worker.html
        - test: 2d.composite.canvas.source-in.html
        - test: 2d.composite.canvas.source-in.worker.html
        - test: 2d.composite.canvas.source-out.html
        - test: 2d.composite.canvas.source-out.worker.html
        - test: 2d.composite.canvas.source-over.html
        - test: 2d.composite.canvas.source-over.worker.html
        - test: 2d.composite.canvas.xor.html
        - test: 2d.composite.canvas.xor.worker.html
        - test: 2d.composite.clip.copy.html
        - test: 2d.composite.clip.copy.worker.html
        - test: 2d.composite.clip.destination-atop.html
        - test: 2d.composite.clip.destination-atop.worker.html
        - test: 2d.composite.clip.destination-in.html
        - test: 2d.composite.clip.destination-in.worker.html
        - test: 2d.composite.clip.destination-out.html
        - test: 2d.composite.clip.destination-out.worker.html
        - test: 2d.composite.clip.destination-over.html
        - test: 2d.composite.clip.destination-over.worker.html
        - test: 2d.composite.clip.lighter.html
        - test: 2d.composite.clip.lighter.worker.html
        - test: 2d.composite.clip.source-atop.html
        - test: 2d.composite.clip.source-atop.worker.html
        - test: 2d.composite.clip.source-in.html
        - test: 2d.composite.clip.source-in.worker.html
        - test: 2d.composite.clip.source-out.html
        - test: 2d.composite.clip.source-out.worker.html
        - test: 2d.composite.clip.source-over.html
        - test: 2d.composite.clip.source-over.worker.html
        - test: 2d.composite.clip.xor.html
        - test: 2d.composite.clip.xor.worker.html
        - test: 2d.composite.globalAlpha.canvas.html
        - test: 2d.composite.globalAlpha.canvas.worker.html
        - test: 2d.composite.globalAlpha.canvascopy.html
        - test: 2d.composite.globalAlpha.canvascopy.worker.html
        - test: 2d.composite.globalAlpha.canvaspattern.html
        - test: 2d.composite.globalAlpha.canvaspattern.worker.html
        - test: 2d.composite.globalAlpha.default.html
        - test: 2d.composite.globalAlpha.default.worker.html
        - test: 2d.composite.globalAlpha.fill.html
        - test: 2d.composite.globalAlpha.fill.worker.html
        - test: 2d.composite.globalAlpha.image.html
        - test: 2d.composite.globalAlpha.image.worker.html
        - test: 2d.composite.globalAlpha.imagepattern.html
        - test: 2d.composite.globalAlpha.imagepattern.worker.html
        - test: 2d.composite.globalAlpha.invalid.html
        - test: 2d.composite.globalAlpha.invalid.worker.html
        - test: 2d.composite.globalAlpha.range.html
        - test: 2d.composite.globalAlpha.range.worker.html
        - test: 2d.composite.image.copy.html
        - test: 2d.composite.image.copy.worker.html
        - test: 2d.composite.image.destination-atop.html
        - test: 2d.composite.image.destination-atop.worker.html
        - test: 2d.composite.image.destination-in.html
        - test: 2d.composite.image.destination-in.worker.html
        - test: 2d.composite.image.destination-out.html
        - test: 2d.composite.image.destination-out.worker.html
        - test: 2d.composite.image.destination-over.html
        - test: 2d.composite.image.destination-over.worker.html
        - test: 2d.composite.image.lighter.html
        - test: 2d.composite.image.lighter.worker.html
        - test: 2d.composite.image.source-atop.html
        - test: 2d.composite.image.source-atop.worker.html
        - test: 2d.composite.image.source-in.html
        - test: 2d.composite.image.source-in.worker.html
        - test: 2d.composite.image.source-out.html
        - test: 2d.composite.image.source-out.worker.html
        - test: 2d.composite.image.source-over.html
        - test: 2d.composite.image.source-over.worker.html
        - test: 2d.composite.image.xor.html
        - test: 2d.composite.image.xor.worker.html
        - test: 2d.composite.operation.casesensitive.html
        - test: 2d.composite.operation.casesensitive.worker.html
        - test: 2d.composite.operation.clear.html
        - test: 2d.composite.operation.clear.worker.html
        - test: 2d.composite.operation.darker.html
        - test: 2d.composite.operation.darker.worker.html
        - test: 2d.composite.operation.default.html
        - test: 2d.composite.operation.default.worker.html
        - test: 2d.composite.operation.get.html
        - test: 2d.composite.operation.get.worker.html
        - test: 2d.composite.operation.highlight.html
        - test: 2d.composite.operation.highlight.worker.html
        - test: 2d.composite.operation.nullsuffix.html
        - test: 2d.composite.operation.nullsuffix.worker.html
        - test: 2d.composite.operation.over.html
        - test: 2d.composite.operation.over.worker.html
        - test: 2d.composite.operation.unrecognised.html
        - test: 2d.composite.operation.unrecognised.worker.html
        - test: 2d.composite.solid.copy.html
        - test: 2d.composite.solid.copy.worker.html
        - test: 2d.composite.solid.destination-atop.html
        - test: 2d.composite.solid.destination-atop.worker.html
        - test: 2d.composite.solid.destination-in.html
        - test: 2d.composite.solid.destination-in.worker.html
        - test: 2d.composite.solid.destination-out.html
        - test: 2d.composite.solid.destination-out.worker.html
        - test: 2d.composite.solid.destination-over.html
        - test: 2d.composite.solid.destination-over.worker.html
        - test: 2d.composite.solid.lighter.html
        - test: 2d.composite.solid.lighter.worker.html
        - test: 2d.composite.solid.source-atop.html
        - test: 2d.composite.solid.source-atop.worker.html
        - test: 2d.composite.solid.source-in.html
        - test: 2d.composite.solid.source-in.worker.html
        - test: 2d.composite.solid.source-out.html
        - test: 2d.composite.solid.source-out.worker.html
        - test: 2d.composite.solid.source-over.html
        - test: 2d.composite.solid.source-over.worker.html
        - test: 2d.composite.solid.xor.html
        - test: 2d.composite.solid.xor.worker.html
        - test: 2d.composite.transparent.copy.html
        - test: 2d.composite.transparent.copy.worker.html
        - test: 2d.composite.transparent.destination-atop.html
        - test: 2d.composite.transparent.destination-atop.worker.html
        - test: 2d.composite.transparent.destination-in.html
        - test: 2d.composite.transparent.destination-in.worker.html
        - test: 2d.composite.transparent.destination-out.html
        - test: 2d.composite.transparent.destination-out.worker.html
        - test: 2d.composite.transparent.destination-over.html
        - test: 2d.composite.transparent.destination-over.worker.html
        - test: 2d.composite.transparent.lighter.html
        - test: 2d.composite.transparent.lighter.worker.html
        - test: 2d.composite.transparent.source-atop.html
        - test: 2d.composite.transparent.source-atop.worker.html
        - test: 2d.composite.transparent.source-in.html
        - test: 2d.composite.transparent.source-in.worker.html
        - test: 2d.composite.transparent.source-out.html
        - test: 2d.composite.transparent.source-out.worker.html
        - test: 2d.composite.transparent.source-over.html
        - test: 2d.composite.transparent.source-over.worker.html
        - test: 2d.composite.transparent.xor.html
        - test: 2d.composite.transparent.xor.worker.html
        - test: 2d.composite.uncovered.fill.copy.html
        - test: 2d.composite.uncovered.fill.copy.worker.html
        - test: 2d.composite.uncovered.fill.destination-atop.html
        - test: 2d.composite.uncovered.fill.destination-atop.worker.html
        - test: 2d.composite.uncovered.fill.destination-in.html
        - test: 2d.composite.uncovered.fill.destination-in.worker.html
        - test: 2d.composite.uncovered.fill.source-in.html
        - test: 2d.composite.uncovered.fill.source-in.worker.html
        - test: 2d.composite.uncovered.fill.source-out.html
        - test: 2d.composite.uncovered.fill.source-out.worker.html
        - test: 2d.composite.uncovered.image.copy.html
        - test: 2d.composite.uncovered.image.copy.worker.html
        - test: 2d.composite.uncovered.image.destination-atop.html
        - test: 2d.composite.uncovered.image.destination-atop.worker.html
        - test: 2d.composite.uncovered.image.destination-in.html
        - test: 2d.composite.uncovered.image.destination-in.worker.html
        - test: 2d.composite.uncovered.image.source-in.html
        - test: 2d.composite.uncovered.image.source-in.worker.html
        - test: 2d.composite.uncovered.image.source-out.html
        - test: 2d.composite.uncovered.image.source-out.worker.html
        - test: 2d.composite.uncovered.nocontext.copy.html
        - test: 2d.composite.uncovered.nocontext.copy.worker.html
        - test: 2d.composite.uncovered.nocontext.destination-atop.html
        - test: 2d.composite.uncovered.nocontext.destination-atop.worker.html
        - test: 2d.composite.uncovered.nocontext.destination-in.html
        - test: 2d.composite.uncovered.nocontext.destination-in.worker.html
        - test: 2d.composite.uncovered.nocontext.source-in.html
        - test: 2d.composite.uncovered.nocontext.source-in.worker.html
        - test: 2d.composite.uncovered.nocontext.source-out.html
        - test: 2d.composite.uncovered.nocontext.source-out.worker.html
        - test: 2d.composite.uncovered.pattern.copy.html
        - test: 2d.composite.uncovered.pattern.copy.worker.html
        - test: 2d.composite.uncovered.pattern.destination-atop.html
        - test: 2d.composite.uncovered.pattern.destination-atop.worker.html
        - test: 2d.composite.uncovered.pattern.destination-in.html
        - test: 2d.composite.uncovered.pattern.destination-in.worker.html
        - test: 2d.composite.uncovered.pattern.source-in.html
        - test: 2d.composite.uncovered.pattern.source-in.worker.html
        - test: 2d.composite.uncovered.pattern.source-out.html
        - test: 2d.composite.uncovered.pattern.source-out.worker.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1688982
      results:
        - test: 2d.composite.uncovered.fill.destination-in.worker.html
          subtest: fill() draws pixels not covered by the source object as (0,0,0,0), and does not leave the pixels unchanged.
