links:
    - product: chrome
      url: https://bugs.chromium.org/p/chromium/issues/detail?id=1230854
      results:
        - test: 2d.imageData.create2.nonfinite.worker.html
        - test: 2d.imageData.get.nonfinite.html
        - test: 2d.imageData.get.nonfinite.worker.html
        - test: 2d.imageData.put.nonfinite.html
        - test: 2d.imageData.put.nonfinite.worker.html
        - test: 2d.imageData.create2.nonfinite.html
    - label: interop-2023-offscreencanvas
      results:
        - test: 2d.imageData.create1.basic.html
        - test: 2d.imageData.create1.basic.worker.html
        - test: 2d.imageData.create1.initial.html
        - test: 2d.imageData.create1.initial.worker.html
        - test: 2d.imageData.create1.zero.html
        - test: 2d.imageData.create1.zero.worker.html
        - test: 2d.imageData.create2.basic.html
        - test: 2d.imageData.create2.basic.worker.html
        - test: 2d.imageData.create2.initial.html
        - test: 2d.imageData.create2.initial.worker.html
        - test: 2d.imageData.create2.large.html
        - test: 2d.imageData.create2.large.worker.html
        - test: 2d.imageData.create2.negative.html
        - test: 2d.imageData.create2.negative.worker.html
        - test: 2d.imageData.create2.nonfinite.html
        - test: 2d.imageData.create2.nonfinite.worker.html
        - test: 2d.imageData.create2.round.html
        - test: 2d.imageData.create2.round.worker.html
        - test: 2d.imageData.create2.zero.html
        - test: 2d.imageData.create2.zero.worker.html
        - test: 2d.imageData.get.basic.html
        - test: 2d.imageData.get.basic.worker.html
        - test: 2d.imageData.get.clamp.html
        - test: 2d.imageData.get.clamp.worker.html
        - test: 2d.imageData.get.length.html
        - test: 2d.imageData.get.length.worker.html
        - test: 2d.imageData.get.nonfinite.html
        - test: 2d.imageData.get.nonfinite.worker.html
        - test: 2d.imageData.get.nonpremul.html
        - test: 2d.imageData.get.nonpremul.worker.html
        - test: 2d.imageData.get.order.alpha.html
        - test: 2d.imageData.get.order.alpha.worker.html
        - test: 2d.imageData.get.order.cols.html
        - test: 2d.imageData.get.order.cols.worker.html
        - test: 2d.imageData.get.order.rgb.html
        - test: 2d.imageData.get.order.rgb.worker.html
        - test: 2d.imageData.get.order.rows.html
        - test: 2d.imageData.get.order.rows.worker.html
        - test: 2d.imageData.get.range.html
        - test: 2d.imageData.get.range.worker.html
        - test: 2d.imageData.get.source.negative.html
        - test: 2d.imageData.get.source.negative.worker.html
        - test: 2d.imageData.get.source.outside.html
        - test: 2d.imageData.get.source.outside.worker.html
        - test: 2d.imageData.get.source.size.html
        - test: 2d.imageData.get.source.size.worker.html
        - test: 2d.imageData.get.unaffected.html
        - test: 2d.imageData.get.unaffected.worker.html
        - test: 2d.imageData.get.zero.html
        - test: 2d.imageData.get.zero.worker.html
        - test: 2d.imageData.object.clamp.html
        - test: 2d.imageData.object.clamp.worker.html
        - test: 2d.imageData.object.nan.html
        - test: 2d.imageData.object.nan.worker.html
        - test: 2d.imageData.object.properties.html
        - test: 2d.imageData.object.properties.worker.html
        - test: 2d.imageData.object.readonly.html
        - test: 2d.imageData.object.readonly.worker.html
        - test: 2d.imageData.object.round.html
        - test: 2d.imageData.object.round.worker.html
        - test: 2d.imageData.object.set.html
        - test: 2d.imageData.object.set.worker.html
        - test: 2d.imageData.object.string.html
        - test: 2d.imageData.object.string.worker.html
        - test: 2d.imageData.object.undefined.html
        - test: 2d.imageData.object.undefined.worker.html
        - test: 2d.imageData.put.alpha.html
        - test: 2d.imageData.put.alpha.worker.html
        - test: 2d.imageData.put.basic.html
        - test: 2d.imageData.put.basic.worker.html
        - test: 2d.imageData.put.clip.html
        - test: 2d.imageData.put.clip.worker.html
        - test: 2d.imageData.put.created.html
        - test: 2d.imageData.put.created.worker.html
        - test: 2d.imageData.put.cross.html
        - test: 2d.imageData.put.cross.worker.html
        - test: 2d.imageData.put.dirty.negative.html
        - test: 2d.imageData.put.dirty.negative.worker.html
        - test: 2d.imageData.put.dirty.outside.html
        - test: 2d.imageData.put.dirty.outside.worker.html
        - test: 2d.imageData.put.dirty.rect1.html
        - test: 2d.imageData.put.dirty.rect1.worker.html
        - test: 2d.imageData.put.dirty.rect2.html
        - test: 2d.imageData.put.dirty.rect2.worker.html
        - test: 2d.imageData.put.dirty.zero.html
        - test: 2d.imageData.put.dirty.zero.worker.html
        - test: 2d.imageData.put.modified.html
        - test: 2d.imageData.put.modified.worker.html
        - test: 2d.imageData.put.nonfinite.html
        - test: 2d.imageData.put.nonfinite.worker.html
        - test: 2d.imageData.put.null.html
        - test: 2d.imageData.put.null.worker.html
        - test: 2d.imageData.put.path.html
        - test: 2d.imageData.put.path.worker.html
        - test: 2d.imageData.put.unaffected.html
        - test: 2d.imageData.put.unaffected.worker.html
        - test: 2d.imageData.put.unchanged.html
        - test: 2d.imageData.put.unchanged.worker.html
        - test: 2d.imageData.put.wrongtype.html
        - test: 2d.imageData.put.wrongtype.worker.html    
